import asyncio
import os
import edge_tts

bedtime_text = """
Selamat malam... 

Rebahkan badanmu... lemaskan otot-otot bahumu... dan tarik napas dalam-dalam...
Malam ini, kita tidak akan pusing memikirkan error atau sintaks yang rumit... 
Biarkan pikiranmu tenang... karena kita akan berpetualang secara perlahan... di sebuah negeri yang damai bernama Laravel...

Laravel... adalah sebuah framework PHP yang begitu lembut dan elegan... 
Bayangkan dirimu sedang duduk santai di malam yang sepi... Angin malam berhembus sepoi-sepoi... suara jangkrik menyapa dari kejauhan...

Perlahan... kita mulai membuka terminal... 
Ketikkan dengan tenang: composer create-project laravel/laravel... 
Lihatlah baris-baris kode mengalir seperti air tenang yang jernih... mendownload paket-paket yang kita butuhkan tanpa terburu-buru...

Selanjutnya... kita berkenalan dengan Routing... 
Routing adalah penunjuk jalan yang ramah... Ketika ada yang mengetikkan slash... Routing akan menyambutnya dengan senyuman dan mengarahkannya ke halaman tujuan... 

Lalu... di dalam keheningan malam... hadir sang Controller... 
Controller yang bijaksana... mengatur logika aplikasi dengan sangat rapi... 
Ia menerima permintaan... memprosesnya perlahan... lalu mengembalikan tampilan view yang indah...

Bayangkan sebuah database... seperti telaga jernih di tengah hutan... 
Di sana... tabel siswa tersimpan dengan rapi... 
Melalui fitur CRUD... Create... Read... Update... dan Delete... 
Data mengalir tenang... bersinergi harmoni dengan Eloquent ORM...

Tak terasa... matamu mulai terasa makin berat... 
Setiap baris kode Blade template meredupkan layarmu secara perlahan... 
Tidak ada error 500... Tidak ada syntax error... 
Semuanya sudah di-handle oleh validasi yang sempurna...

Biarkan jalannya aplikasi ini membawa pikiranmu melayang... menuju alam mimpi yang indah...
Selamat tidur... programmer handal... 
Besok pagi... Laravel-mu akan berjalan dengan sempurna...
"""

# Voice preset pilihan: Sebastian (actor51) - Warm & Soothing
CHOSEN_VOICE_NAME = "Sebastian"
CHOSEN_ACTOR_ID = "actor51"

async def generate_bedtime_audiobook():
    # Menggunakan suara Ardi/Sebastian dengan tempo pelan (-20%)
    voice = "id-ID-ArdiNeural"
    
    script_dir = os.path.dirname(os.path.abspath(__file__))
    output_file = os.path.join(script_dir, "Laravel_Pengantar_Tidur.mp3")
    
    communicate = edge_tts.Communicate(bedtime_text, voice, rate="-20%", pitch="-2Hz")
    await communicate.save(output_file)
    print(f"Audiobook pengantar tidur berhasil dibuat di {output_file} menggunakan voice {CHOSEN_VOICE_NAME} ({CHOSEN_ACTOR_ID})!")

if __name__ == "__main__":
    asyncio.run(generate_bedtime_audiobook())
